---
openapi: 3.0.0
info:
  title: SOLID Documentation
  description: This is an API for the first challenge
  version: 1.0.0
  contact:
    email: ricardo85x@gmail.com
paths:
  "/users/":
    post:
      tags:
        - User
      summary: Create a User
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              example:
                name: Ricardo
                email: ricardo@email.com
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  admin:
                    type: boolean
        "400":
          description: User [email] already exists
    get:
      tags:
        - User
      summary: List all users
      description: List all users (must be admin)
      parameters:
        - name: user_id
          in: header
          description: User ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    admin:
                      type: boolean
                    created_at:
                      type: string
                    updated_at:
                      type: string
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: string              
  "/users/{user_id}/admin":
    patch:
      tags:
        - User
      summary: Turn a user into admin
      description: Turn a user into admin
      parameters:
        - name: user_id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  admin:
                    type: boolean
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  
        "404":
          description: User not found
  "/users/{user_id}":
    get:
      tags: 
        - User
      summary: "Show user profile"
      description: "Show user profile"
      parameters:
        - name: user_id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  admin:
                    type: boolean
                  created_at:
                    type: string
                  updated_at:
                    type: string
       
   